### ISSUE TITLE
Error: ENOSPC

### ISSUE THREAD

**Issue by capsulecorplab** [cypress-io/cypress-example-kitchensink#129]
Followed steps as outlined in https://github.com/cypress-io/cypress-example-kitchensink#1-fork-this-repo
Opened new terminal window to run `npm run cy:open` to open up cypress test runner, but encounter following error when attempting to run any of the tests

```
$ npm run cy:open

> cypress-example-kitchensink@1.0.2 cy:open /home/saiyaman/gitrepos/cloned/cypress-example-kitchensink
> cypress open

GET /__/ 200 145.607 ms - -
GET /__cypress/runner/cypress_runner.css 200 382.874 ms - -
GET /__cypress/runner/cypress_runner.js 200 1099.415 ms - -
GET /__cypress/static/favicon.ico 200 6.336 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.7.0 200 2.492 ms - 77160
GET /__cypress/iframes/integration/examples/actions.spec.js 200 15.477 ms - 745
{ Error: watch /home/saiyaman/gitrepos/cloned/cypress-example-kitchensink/package.json ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/saiyaman/.cache/Cypress/3.1.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/saiyaman/.cache/Cypress/3.1.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/saiyaman/.cache/Cypress/3.1.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/saiyaman/.cache/Cypress/3.1.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/saiyaman/.cache/Cypress/3.1.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/saiyaman/.cache/Cypress/3.1.0/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)

  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/saiyaman/gitrepos/cloned/cypress-example-kitchensink/package.json',
  filename: '/home/saiyaman/gitrepos/cloned/cypress-example-kitchensink/package.json' }
Error: watch /home/saiyaman/gitrepos/cloned/cypress-example-kitchensink/package.json ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/saiyaman/.cache/Cypress/3.1.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/saiyaman/.cache/Cypress/3.1.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/saiyaman/.cache/Cypress/3.1.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/saiyaman/.cache/Cypress/3.1.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/saiyaman/.cache/Cypress/3.1.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/saiyaman/.cache/Cypress/3.1.0/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
```

**Comment by capsulecorplab** [comment]
Resolved issue. Turned out it was a limit with Linux's inotify. 
https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
