### ISSUE TITLE
Set up TeamCity CI Example

### ISSUE THREAD

**Issue by RandallKent** [cypress-io/cypress-example-kitchensink#144]

**Comment by bahmutov** [comment]
yeah, @RandallKent if you can find a paid TeamCity CI, I would easily set this up I think, I submitted us to free open source teamcity CI project but they never got back to me :( https://github.com/cypress-io/cypress-internal/issues/173

**Comment by bahmutov** [comment]
- [ ] @RandallKent should find TeamCity CI service and open an account there and add this project
- [ ] @bahmutov can do the rest

**Comment by bahmutov** [comment]
Trying to run TeamCity locally (server and an agent) using Docker containers to build this project

**Comment by bahmutov** [comment]
<img width="983" alt="screen shot 2018-11-09 at 4 36 21 pm" src="https://user-images.githubusercontent.com/2212006/48289474-9d6b6800-e43d-11e8-9832-da34f3a99f2f.png">

simple recording is working but missing some commit information

**Comment by bahmutov** [comment]
Got debug output from 3.1.1
```
[17:06:31][Step 1/1]   commit-info commit-info in folder /opt/buildagent/work/30c5483c494975d8 +0ms
[17:06:31][Step 1/1]   commit-info using Git tool to find branch +0ms
[17:06:31][Step 1/1]   commit-info running git command: git rev-parse --abbrev-ref HEAD +0ms
[17:06:31][Step 1/1]   commit-info in folder /opt/buildagent/work/30c5483c494975d8 +0ms
[17:06:31][Step 1/1]   commit-info running git command: git show -s --pretty=%B +2ms
[17:06:31][Step 1/1]   commit-info in folder /opt/buildagent/work/30c5483c494975d8 +0ms
[17:06:31][Step 1/1]   commit-info running git command: git show -s --pretty=%ae +0ms
[17:06:31][Step 1/1]   commit-info in folder /opt/buildagent/work/30c5483c494975d8 +0ms
[17:06:31][Step 1/1]   commit-info running git command: git show -s --pretty=%an +0ms
[17:06:31][Step 1/1]   commit-info in folder /opt/buildagent/work/30c5483c494975d8 +0ms
[17:06:31][Step 1/1]   commit-info running git command: git show -s --pretty=%H +0ms
[17:06:31][Step 1/1]   commit-info in folder /opt/buildagent/work/30c5483c494975d8 +0ms
[17:06:31][Step 1/1]   commit-info running git command: git config --get remote.origin.url +1ms
[17:06:31][Step 1/1]   commit-info in folder /opt/buildagent/work/30c5483c494975d8 +0ms
[17:06:31][Step 1/1]   commit-info git stdout: master +87ms
[17:06:31][Step 1/1]   commit-info got an error running command "git show -s --pretty=%B" in folder "/opt/buildagent/work/30c5483c494975d8" +0ms
[17:06:31][Step 1/1]   commit-info Error: Command failed: /bin/sh -c git show -s --pretty=%B
[17:06:31][Step 1/1]   commit-info error: object directory /opt/buildagent/system/git/git-8B497B35.git/objects does not exist; check .git/objects/info/alternates.
[17:06:31][Step 1/1]   commit-info fatal: bad object HEAD
[17:06:31][Step 1/1]   commit-info 
[17:06:31][Step 1/1]   commit-info 
[17:06:31][Step 1/1]   commit-info     at Promise.all.then.arr (/root/.cache/Cypress/3.1.1/Cypress/resources/app/packages/server/node_modules/execa/index.js:236:11)
[17:06:31][Step 1/1]   commit-info     at <anonymous>:null:null
[17:06:31][Step 1/1]   commit-info     at process._tickCallback (internal/process/next_tick.js:188:7)
[17:06:31][Step 1/1]   commit-info  +0ms
[17:06:31][Step 1/1]   commit-info got an error running command "git show -s --pretty=%ae" in folder "/opt/buildagent/work/30c5483c494975d8" +0ms
[17:06:31][Step 1/1]   commit-info Error: Command failed: /bin/sh -c git show -s --pretty=%ae
[17:06:31][Step 1/1]   commit-info error: object directory /opt/buildagent/system/git/git-8B497B35.git/objects does not exist; check .git/objects/info/alternates.
[17:06:31][Step 1/1]   commit-info fatal: bad object HEAD
[17:06:31][Step 1/1]   commit-info 
[17:06:31][Step 1/1]   commit-info 
[17:06:31][Step 1/1]   commit-info     at Promise.all.then.arr (/root/.cache/Cypress/3.1.1/Cypress/resources/app/packages/server/node_modules/execa/index.js:236:11)
[17:06:31][Step 1/1]   commit-info     at <anonymous>:null:null
[17:06:31][Step 1/1]   commit-info     at process._tickCallback (internal/process/next_tick.js:188:7)
[17:06:31][Step 1/1]   commit-info  +0ms
[17:06:31][Step 1/1]   commit-info got an error running command "git show -s --pretty=%an" in folder "/opt/buildagent/work/30c5483c494975d8" +1ms
[17:06:31][Step 1/1]   commit-info Error: Command failed: /bin/sh -c git show -s --pretty=%an
[17:06:31][Step 1/1]   commit-info error: object directory /opt/buildagent/system/git/git-8B497B35.git/objects does not exist; check .git/objects/info/alternates.
[17:06:31][Step 1/1]   commit-info fatal: bad object HEAD
[17:06:31][Step 1/1]   commit-info 
[17:06:31][Step 1/1]   commit-info 
[17:06:31][Step 1/1]   commit-info     at Promise.all.then.arr (/root/.cache/Cypress/3.1.1/Cypress/resources/app/packages/server/node_modules/execa/index.js:236:11)
[17:06:31][Step 1/1]   commit-info     at <anonymous>:null:null
[17:06:31][Step 1/1]   commit-info     at process._tickCallback (internal/process/next_tick.js:188:7)
[17:06:31][Step 1/1]   commit-info  +0ms
[17:06:31][Step 1/1]   commit-info got an error running command "git show -s --pretty=%H" in folder "/opt/buildagent/work/30c5483c494975d8" +2ms
[17:06:31][Step 1/1]   commit-info Error: Command failed: /bin/sh -c git show -s --pretty=%H
[17:06:31][Step 1/1]   commit-info error: object directory /opt/buildagent/system/git/git-8B497B35.git/objects does not exist; check .git/objects/info/alternates.
[17:06:31][Step 1/1]   commit-info fatal: bad object HEAD
[17:06:31][Step 1/1]   commit-info 
[17:06:31][Step 1/1]   commit-info 
[17:06:31][Step 1/1]   commit-info     at Promise.all.then.arr (/root/.cache/Cypress/3.1.1/Cypress/resources/app/packages/server/node_modules/execa/index.js:236:11)
[17:06:31][Step 1/1]   commit-info     at <anonymous>:null:null
[17:06:31][Step 1/1]   commit-info     at process._tickCallback (internal/process/next_tick.js:188:7)
[17:06:31][Step 1/1]   commit-info  +0ms
```

**Comment by philipjrosen** [comment]
@bahmutov is it currently possible to run cypress on teamcity?  My team would like to explore using cypress instead of selenium, but I need to make sure we won't have any problems integrating with teamcity.

**Comment by bahmutov** [comment]
sure, I am running the teamcity as shown above using Docker containers from cypress-docker-images - they question is that we cannot find commercial TeamCity CI provider to have an up to date public example

**Comment by philipjrosen** [comment]
Thanks!
