### ISSUE TITLE
Set up Mac build on SemaphoreCI v2

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-kitchensink#269]
To confirm https://github.com/cypress-io/cypress/issues/918#issuecomment-505848402 issue

```
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
2019-06-26 05:07:07.441 Cypress[5288:16143] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.3.1                                                                              │
  │ Browser:    Electron 61 (headless)                                                             │
  │ Specs:      1 found (swithing_views_spec.js)                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running: swithing_views_spec.js...                                           (1 of 1)
Cannot create BrowserWindow before app is ready
Error: Cannot create BrowserWindow before app is ready
    at Object._newBrowserWindow (/Users/semaphore/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/gui/windows.js:104:14)
    at Object.create (/Users/semaphore/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/gui/windows.js:207:18)
    at Object._render (/Users/semaphore/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/electron.js:87:21)
    at /Users/semaphore/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/electron.js:214:24
    at <anonymous>:null:null
```

**Comment by bahmutov** [comment]
Perfect, I can recreate the problem, see https://cypress-io.semaphoreci.com/jobs/73db74af-dbc3-4b2a-836c-42d59f3bf353

<img width="1391" alt="Screen Shot 2019-07-12 at 10 32 49 AM" src="https://user-images.githubusercontent.com/2212006/61135937-9dba7800-a490-11e9-8cc0-85c9e19d8f68.png">

I have disabled the Mac block for now, but can be re-enabled to test, see https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.semaphore/semaphore.yml#L14
