### ISSUE TITLE
not possible to set up Jenkins CI

### ISSUE THREAD

**Issue by pishtik** [cypress-io/cypress-example-kitchensink#334]
Hi I am trying to run cypress-kitchensink I added pipeline job , I always end with this : 
I cannot get test and app running 

````
Started by user admin
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /var/jenkins_home/workspace/cy2
[Pipeline] {
[Pipeline] isUnix
[Pipeline] sh
+ docker inspect -f . cypress/base:12.6.0
.
[Pipeline] withDockerContainer
Jenkins seems to be running inside container a796920fc28305901602abc8aa699ecd5836a1e6ed3b4c3fa21269118563c197
$ docker run -t -d -u 0:0 -w /var/jenkins_home/workspace/cy2 --volumes-from a796920fc28305901602abc8aa699ecd5836a1e6ed3b4c3fa21269118563c197 -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** cypress/base:12.6.0 cat
$ docker top 26c8b611e06484def210859b9731c4b443cb992610ed99447670bbcb0d06cf25 -eo pid,comm
[Pipeline] {
[Pipeline] stage
[Pipeline] { (build)
[Pipeline] echo
Running build 9 on http://localhost:8080/
[Pipeline] sh
+ npm ci
npm WARN prepare removing existing node_modules/ before installation

> core-js@2.6.10 postinstall /var/jenkins_home/workspace/cy2/node_modules/core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> husky@1.3.1 install /var/jenkins_home/workspace/cy2/node_modules/husky
> node husky install

husky > setting up git hooks
CI detected, skipping Git hooks installation.

> cypress@3.7.0 postinstall /var/jenkins_home/workspace/cy2/node_modules/cypress
> node index.js --exec install


Cypress 3.7.0 is installed in /root/.cache/Cypress/3.7.0

added 893 packages in 48.631s
[Pipeline] sh
+ npm run cy:verify

> cypress-example-kitchensink@0.0.0-development cy:verify /var/jenkins_home/workspace/cy2
> cypress verify

[?25l[16:50:17]  Verifying Cypress can run /root/.cache/Cypress/3.7.0/Cypress [started]
[16:50:20]  Verifying Cypress can run /root/.cache/Cypress/3.7.0/Cypress [completed]
[?25h[?25h
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (start local server)
[Pipeline] sh
+ nohup npm run start:ci
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (cypress parallel tests)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] echo
Stopping local server
[Pipeline] sh
+ pkill -f http-server
Error when executing always post condition:
hudson.AbortException: script returned exit code 1
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:658)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:604)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:548)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[Pipeline] }
[Pipeline] // stage
[Pipeline] }
$ docker stop --time=1 26c8b611e06484def210859b9731c4b443cb992610ed99447670bbcb0d06cf25
$ docker rm -f 26c8b611e06484def210859b9731c4b443cb992610ed99447670bbcb0d06cf25
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: cypress-example-kitchensink-record-key
Finished: FAILURE
```

**Comment by pishtik** [comment]
my bad , the issue was , not recognizable credentials thats why the issue  ERROR: cypress-example-kitchensink-record-key  at the end , I followed this tutorial 
https://support.cloudbees.com/hc/en-us/articles/203802500-Injecting-Secrets-into-Jenkins-Build-Jobs
afterwards it worked fine
