### ISSUE TITLE
Firefox video recording sometimes fails

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-kitchensink#476]
```
  Running:  examples\actions.spec.js                                                       (1 of 19)
  Estimated: 21 seconds


  Actions
Warning: We failed to record the video.

This error will not alter the exit code.

Error: ffmpeg exited with code 1: pipe:0: Function not implemented

    at ChildProcess.<anonymous> (C:\Users\circleci\AppData\Local\Cypress\Cache\6.7.1\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

<img width="1128" alt="Screen Shot 2021-03-16 at 4 11 41 PM" src="https://user-images.githubusercontent.com/2212006/111373491-4e1f4d00-8672-11eb-8079-44cd94e6325a.png">

**Comment by MikeMcC399** [comment]
Cypress no longer records videos by default.

- additional Firefox video recording does not work with current Firefox browser versions https://github.com/cypress-io/cypress/issues/18415
